name: "[PROD] Build&Deploy"
on:
  push:
    branches:
      - prod
jobs:
  build:
    uses: KeenMate/gha-shared/.github/workflows/deploy-docker-image.yml@master
    secrets: inherit
    with:
      image-name: pure-admin
      image-tag: production
      deployment-host: web-03.km8.vm
      deployment-dir: pure-admin-prod
